- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Aptly is installed.
  apt: "name={{ item }} state={{ aptly_packages_state }}"
  with_items: "{{ aptly_packages }}"
