- name: Установка пакетов
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items: "{{ packages }}"
  tags:
    - install

- name: Забрать rndc.key (используется в dhcpd.conf.j2)
  slurp:
    src: /etc/bind/rndc.key
  register: rndc

- debug: msg="{{ rndc['content'] | b64decode }}"

- name: Файл кофигурации Bind9
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: bind/10.0.0.in-addr.arpa.zone.j2
      dest: /etc/bind/{{ domain }}.arpa.zone
    - src: bind/db.domain.j2
      dest: "/etc/bind/db.{{ domain }}"
    - src: bind/named.conf.local.j2
      dest: /etc/bind/named.conf.local
    - src: bind/named.conf.options.j2
      dest: /etc/bind/named.conf.options
  notify:
    - Перезапуск Bind9

- name: Файл кофигурации dhcpd
  template:
    src: dhcp/dhcpd.conf.j2
    dest: "/etc/dhcp/dhcpd.conf"
    mode: u=rwx,g=rx,o=rx

- name: Файл кофигурации default dhcpd
  template:
    src: dhcp/isc-dhcp-server.j2
    dest: "/etc/default/isc-dhcp-server"
    mode: u=rwx,g=rx,o=rx

- name: права на запимь для bind в /etc/bind/
  file:
    path: /etc/bind/
    state: touch
    mode: "g+rw"

- name: Перезапуск dhcpd
  service:
    name: isc-dhcp-server
    state: restarted

- name: Перезапуск Bind9
  service:
    name: bind9
    state: restarted
