  # - debug: msg="{{host_list}}"
  - name: Generate SSH keys
    shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
    args:
      creates: /root/.ssh/id_rsa

  - name: Установить пакеты
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"

  - name: Файл hosts
    template:
      src: hosts.j2
      dest: "/etc/hosts"
      mode: u=rwx,g=rx,o=rx

  - name: Файл кофигурации сети
    template:
      src: interfaces.j2
      dest: "/etc/network/interfaces"
      mode: u=rwx,g=rx,o=rx

  - name: Перезапуск сети
    service:
      name: networking
      state: restarted

  - name: Файл кофигурации dhcpd
    template:
      src: dhcpd/dhcpd.conf.j2
      dest: "/etc/dhcp/dhcpd.conf"
      mode: u=rwx,g=rx,o=rx
    # with_subelements:
    #   - "{{object_list.groups}}"

  - name: Файл кофигурации default dhcpd
    template:
      src: dhcpd/isc-dhcp-server.j2
      dest: "/etc/default/isc-dhcp-server"
      mode: u=rwx,g=rx,o=rx

  - name: Перезапуск dhcpd
    service:
      name: isc-dhcp-server
      state: restarted

  - name: Создать структуру каталогов для pxe
    file:
      path: "{{ item }}"
      state: directory
      mode: u=rwx,g=rwx,o=rwx
    with_items:
      - "{{ data.netinstall }}/pxelinux.cfg/"

  - name: Получить список хостов из всех груп (костыль1)
    set_fact:
      host_list: "{{ host_list | default({}) | combine(item.hosts,  recursive=True) }}"
    with_items: "{{object_list.groups.values()}}"
    tags:
      - debug


  - name: Получить список хостов из всех груп (костыль2)
    set_fact:
      host_list: "{{ host_list | default({}) | combine( object_list.groups['ex'].hosts,  recursive=True) }}"
    tags:
      - debug


#  - name: Получить список хостов из всех груп (костыль3)
#    set_fact:
#      host_list: "{{ host_list | default({}) | combine( object_list.groups[item.key].hosts ) }}"
#    with_dict:
#      "{{object_list.groups}}"
#    tags:
#      - debug

  # - debug: msg="{{ host_list }}"
  #   tags:
  #     - debug

  - name: Файл кофигурации для pxe
    template:
      src: tftpd/default.j2
      dest: "{{ data.netinstall }}/pxelinux.cfg/01-{{ item.1.mac }}"
      mode: u=rwx,g=rx,o=rx
    with_subelements:
      - "{{ host_list.values() }}"
      - network

  - name: Файл кофигурации для tftpd
    template:
      src: tftpd/inetd.conf.j2
      dest: "/etc/inetd.conf"
      mode: u=rwx,g=rx,o=rx

  - name: Перезапуск tftpd
    service:
      name: openbsd-inetd
      state: restarted

  - name: Настроить Nginx
    include_role:
      name: nginx

  - name: Файл кофигурации для Nginx(netinstall)
    template:
      src: nginx/nginx-netinstall.conf.j2
      dest: "/etc/nginx/conf.d/netinstall.conf"
      mode: u=rwx,g=rx,o=rx
    notify:
      - Перезапуск Nginx

  - name: Файл кофигурации для Nginx(repository)
    template:
      src: nginx/nginx-repo.conf.j2
      dest: "/etc/nginx/conf.d/repo.conf"
      mode: u=rwx,g=rx,o=rx
    notify:
      - Перезапуск Nginx

  - name: Файл кофигурации для Nginx(sc-repository)
    template:
      src: nginx/nginx-repo-sc.conf.j2
      dest: "/etc/nginx/conf.d/repo-sc.conf"
      mode: u=rwx,g=rx,o=rx
    notify:
      - Перезапуск Nginx

  - name: Файл кофигурации для preseed
    template:
      src: preseed.cfg.j2
      dest: "{{data.netinstall}}/preseed.cfg"
      mode: u=rwx,g=rx,o=rx
