---
# Общая роль
  - name: install debconf-utill
    apt:
      name: debconf-utils
    tags:
      - install

  - name: generate locale
    locale_gen:
      name: "{{item}}"
      state: present
    with_items: "{{ locales_list }}"
    tags:
      - config

  - name: drop locales (Обход проблемы с неинтерактивным dpkg-reconfigure)
    command: "update-locale LANG="
    tags:
      - config

  - name: set default locale
    debconf:
      name: locales
      question: locales/default_environment_locale
      value: "{{ locale }}"
      vtype: select
    tags:
      - config

  - name: reconfigure locales
    command: "dpkg-reconfigure locales -f noninteractive"
    tags:
      - config

  - name: Set timezone
    timezone:
      name: "{{ timezone }}"
    tags:
      - config
