---
all:
  children:
    RootCellar:
      children:
        common:
          hosts:
            scb-oauth.rc.local:
            scb-exd.rc.local:
            scb-mupp.rc.local:
            scb-integ.rc.local:
            scb-portal.rc.local:
        config-interfaces:
          hosts:
            scb-oauth.rc.local:
            scb-exd.rc.local:
            scb-mupp.rc.local:
            scb-integ.rc.local:
            scb-portal.rc.local:
          vars:
            interfaces_ether_interfaces:
              - device: eth0
                bootproto: dhcp
      vars:
        ansible_user: sysadm
        ansible_ssh_pass: zaq!2345
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_user: root
        ansible_become_pass: zaq!2345
