---
all:
  vars:
    ansible_user: sysadm
    ansible_ssh_pass: xsw!2345
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_pass: xsw!2345
  children:
    dyn-dns-dhcp:
      hosts:
        10.0.0.254:
          domain: smartsmalls
          dns: 10.0.0.254
          dhcp_interface: ens18
    addusers:
      hosts:
        ns.smartsmalls:
        ldap.smartsmalls:
        gitlab.smartsmalls:
        jira.smartsmalls:
        svn.smartsmalls:
        zabbix.smartsmalls:
        nginx.smartsmalls:
        bareos.smartsmalls:
        openvpn.smartsmalls:
        green.smartsmalls:
      vars:
        ansible_become_method: su
        users:
          - name: sysadm
            pass: $6$.taj9R7pEMDHeGf2$oHOM0mi9gSn6OjEnrSE4pD0T32ScPn3zSrIyb37onFe7iImdCF9ew43/pOZ5zdGgo68jqWU2elOjQnljAdUDg.
            shell: /bin/bash
          - name: knurov
            pass: $6$2V9wExiHRDOdLNRX$siApJGAXctoumAaA15hwfdzLmFU/j1epEpxyDJUrZ3ezelEte5bafiMgZ3OQVXmT25sGSxIT4wig0BAL6oF6U.
            shell: /bin/bash
          - name: vtorov
            pass: $6$.taj9R7pEMDHeGf2$oHOM0mi9gSn6OjEnrSE4pD0T32ScPn3zSrIyb37onFe7iImdCF9ew43/pOZ5zdGgo68jqWU2elOjQnljAdUDg.
            shell: /bin/bash
          - name: aleshkin
            pass: $6$.taj9R7pEMDHeGf2$oHOM0mi9gSn6OjEnrSE4pD0T32ScPn3zSrIyb37onFe7iImdCF9ew43/pOZ5zdGgo68jqWU2elOjQnljAdUDg.
            shell: /bin/bash

    common:
      hosts:
        ns.smartsmalls:
        openvpn.smartsmalls:
        ldap.smartsmalls:
        gitlab.smartsmalls:
        jira.smartsmalls:
        svn.smartsmalls:
        zabbix.smartsmalls:
        nginx.smartsmalls:
        bareos.smartsmalls:
        green.smartsmalls:

    server-tools:
      hosts:
        ns.smartsmalls:
        openvpn.smartsmalls:
        ldap.smartsmalls:
        gitlab.smartsmalls:
        jira.smartsmalls:
        svn.smartsmalls:
        zabbix.smartsmalls:
        nginx.smartsmalls:
        bareos.smartsmalls:
        green.smartsmalls:

    docker:
      hosts:
        green.smartsmalls:
          docker_edition: "ce"
          docker_channel: "edge"
          docker_install_docker_compose: True
          docker_compose_version: "1.21.0"
          docker_users: sysadm
          docker_cron_tasks:
            - job: docker system prune -f
              name: "Docker clean up"
              schedule: ["0", "0", "*", "*", "0"]
          docker_daemon_options: --dns 10.0.0.254
          docker_daemon_environment: NO_PROXY=localhost,127.0.0.1
          docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
          docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
          docker_apt_package_name: "{{ docker_version }}~{{ docker_edition }}~3-0~{{ ansible_distribution | lower }}"
          docker_apt_cache_time: 86400

    openvpn:
      hosts:
        openvpn.smartsmalls:
          domain: smartsmalls
          dns: 10.0.0.254
          vpnnet: 10.0.99.0
          interface: eth0
    ldap:
      hosts:
        ldap.smartsmalls:
          service:
            - description: Каталог пользователей и групп
              logo: fa-users
              title: ldap
          dn: "dc=4dir,dc=com"
          domain: "4dir.com"
          bind_pw: Xsw!2345
          system_dn: systemaccount
          system_pw: systempassword
          sysadm_name: sysadm
          sysadm_pw: Xsw!2345
          sysadm_email: "sysadm@smartsmalls.com"
    gitlab:
      hosts:
        gitlab.smartsmalls:
          service:
            - description: Репозитории GIT
              logo: fa-gitlab
              title: GitLab
    jira:
      hosts:
        jira.smartsmalls:
          service:
            - description: Трекер и управление проектами
              logo: fa-bug
              title: Jira
    subversion:
      hosts:
        svn.smartsmalls:
          service:
            - description: Репозиторий с документацией
              protocol: http
              logo: fa-file
              title: SVN
            - description: Админисстрирование svn
              cname: svnadmin.smartsmalls
              logo: fa-file
              title: SVN Admin
              group: admins
    zabbix:
      hosts:
        zabbix.smartsmalls:
          service:
            - description: Мониторинг инфраструктуры
              logo: fa-heartbeat
              title: Zabbix
              group: admins
    nginx-proxy:
      hosts:
        nginx.smartsmalls:

    bareos:
      hosts:
        bareos.smartsmalls:
          service:
            - description: Резервное копирование
              logo: fa-save
              title: Bareos
              group: admins
    proxmox:
      hosts:
        proxmox.smartsmalls.com:
          service:
            - description: Виртуализация qemu/lxc
              logo: fa-server
              title: Proxmox
              group: admins

    landingpage:
      hosts:
        ns.smartsmalls:
          title: Инфраструктура разработки
          description: Все что нужно для полного цикла разработки
          ou: Кочевые компуторщики
          subdomain: home.* start.*
          contacts:
            phones:
              - +7(000)000-00-00
              - +7(000)000-00-01
            emails:
              - sysadm@smartsmalls.com
            message: Что-то пошло не така - есть телефон и почта.

    greenenergy:
      hosts:
        green.smartsmalls:
          service:
            - description: Стенд для GreeenEnergy
              logo: fa-desktop
              title: Buyer
              cname: buyer.green.smartsmalls
              group: stands
            - description: Стенд для GreeenEnergy
              logo: fa-desktop
              title: Operator
              cname: operator.green.smartsmalls
              group: stands
            - description: Стенд для GreeenEnergy
              logo: fa-desktop
              title: Producer
              cname: producer.green.smartsmalls
              group: stands
