---
all:
  children:
    RootCellar:
      children:
        postgres:
          hosts:
            piv-internal.rc.local:
        bareos-fd:
          hosts:
            piv-internal.rc.local:
        bareos-dir:
          hosts:
            bareos.rc.local:


      vars:
        postgres_user: postgres
        postgres_password: postgres
        ansible_user: sysadm
        ansible_ssh_pass: zaq!2345
        ansible_become: true
        ansible_become_method: sudo
        # ansible_become_user: root
        ansible_become_pass: zaq!2345
