---
apache_service: apache2
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2
apache_default_vhost_filename: 000-default

apache_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-auth-pam

apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"

apache_listen_port: 80
apache_vhosts:
  - {servername: "example.com", documentroot: "/var/www/"}
