---
# Роль директора для bareos
  - name: Обновить метаданные репозитория deb
    apt:
      update_cache: yes
    tags:
      - install

  - name: Установить пакеты из списка
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    tags:
      - install

  - name: Установить LAM c оф сайта
    apt:
      deb: https://github.com/LDAPAccountManager/lam/releases/download/untagged-0f11e4b04e249cac51c5/ldap-account-manager_6.4-1_all.deb
      state: present
    tags:
      - install

  - name: Включить автозапуск службы slapd
    service:
      name: slapd
      enabled: yes
      state: started
    tags:
      - install

  # - name: Создать каталог для кастомных фактов
  #   file:
  #     path: "/etc/ansible/facts.d"
  #     state: "directory"
  #   tags:
  #     - config
  #
  # - name: записать в факты об установленных сервисах
  #   ini_file:
  #     path: /etc/ansible/facts.d/services.fact
  #     state: present
  #     create: yes
  #     section: general
  #     option: "{{ item }}"
  #     value: True
  #     no_extra_spaces: yes
  #   with_items: "{{ packages }}"
  #   tags:
  #     - config

#  - name: setup
#    setup: filter=ansible_local
#    tags:
#      - config
