---
# Роль директора для bareos
  - name: Обновить метаданные репозитория deb
    apt:
      update_cache: yes
    tags:
      - install

  - name: Настройка OPENLDAP
    block:
      - debconf: name='slapd' question='slapd/password2' vtype='password' value='{{ bind_pw }}'
      - debconf: name='slapd' question='slapd/internal/generated_adminpw' vtype='password' value='{{ bind_pw }}'
      - debconf: name='slapd' question='slapd/internal/adminpw' vtype='password' value='{{ bind_pw }}'
      - debconf: name='slapd' question='slapd/password1' vtype='password' value='{{ bind_pw }}'
      - debconf: name='slapd' question='slapd/unsafe_selfwrite_acl' vtype='note' value=''
      - debconf: name='slapd' question='slapd/upgrade_slapcat_failure' vtype='error' value=''
      - debconf: name='slapd' question='slapd/invalid_config' vtype='boolean' value='true'
      - debconf: name='slapd' question='slapd/password_mismatch' vtype='note' value=''
      - debconf: name='slapd' question='slapd/dump_database' vtype='select' value='when needed'
      - debconf: name='slapd' question='slapd/no_configuration' vtype='boolean' value='false'
      - debconf: name='slapd' question='slapd/purge_database' vtype='boolean' value='true'
      - debconf: name='slapd' question='slapd/domain' vtype='string' value='{{domain}}'
      - debconf: name='slapd' question='slapd/move_old_database' vtype='boolean' value='true'
      - debconf: name='slapd' question='slapd/ppolicy_schema_needs_update' vtype='select' value='abort installation'
      - debconf: name='slapd' question='slapd/backend' vtype='select' value='MDB'
      - debconf: name='slapd' question='shared/organization' vtype='string' value='{{domain}}'
      - debconf: name='slapd' question='slapd/dump_database_destdir' vtype='string' value='/var/backups/slapd-VERSION'
    tags:
      - debconf

  - name: Установить пакеты из списка
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    tags:
      - install

  - name: Включить автозапуск службы slapd
    service:
      name: slapd
      enabled: yes
      state: started
    tags:
      - install

  - name: Установить LAM c оф сайта
    apt:
      deb: https://github.com/LDAPAccountManager/lam/releases/download/untagged-0f11e4b04e249cac51c5/ldap-account-manager_6.4-1_all.deb
      state: present
    tags:
      - install

  - name: Добавить Ветку с пользователями в LDAP
    ldap_entry:
      dn: "ou=People,{{ dn }}"
      objectClass:
        - organizationalUnit
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"

  - name: Добавить Ветку с группами в LDAP
    ldap_entry:
      dn: "ou=group,{{ dn }}"
      objectClass:
        - organizationalUnit
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"

  - name: Добавить группу users в LDAP
    ldap_entry:
      dn: "cn=users,ou=group,{{ dn }}"
      objectClass:
        - posixGroup
      attributes:
        gidNumber: 10000
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"

  - name: Удалить системную учетную запись
    ldap_entry:
      dn: "uid=systemaccount,{{ dn }}"
      state: absent
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"
    tags:
      - system_account


  - name: Добавить системную учетную запись
    ldap_entry:
      dn: "uid=systemaccount,{{ dn }}"
      objectClass:
        - simpleSecurityObject
        - account
      attributes:
        userPassword: "{{ system_pw }}"
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"
    tags:
      - system_account

  - name: Добавить группу ldapadmins
    ldap_entry:
      dn: "cn=ldapadmins,ou=group,{{ dn }}"
      objectClass:
        - groupOfNames
      attributes:
        member: ""
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"
    tags:
      - system_account

  - name: Дать права на запись группе ldapadmins
    ldap_attr:
      dn: olcDatabase={1}mdb,cn=config
      name: olcAccess
      values:
        - '{3}to *   by group="cn=ldapadmins,ou=group,{{ dn }}" manage by self write by * read'
      state: present
      server_uri: ldap://localhost/
      bind_dn: "cn=admin,{{ dn }}"
      bind_pw: "{{ bind_pw }}"
    tags:
      - system_account

# olcAccess: {0}to attrs=userPassword by self write by anonymous auth by * non
#  e
# olcAccess: {1}to attrs=shadowLastChange by self write by * read
# olcAccess: {2}to * by * read


  - name: Добавить конфиг в nginx
    block:
      - template:
          src: "lam.j2"
          dest: "/etc/nginx/sites-available/lam"
        notify:
          - restart nginx
      - file:
          src: /etc/nginx/sites-available/lam
          path: /etc/nginx/sites-enabled/lam
          state: link
        notify:
          - restart nginx
      - file:
          path: /etc/nginx/sites-enabled/default
          state: absent

  - name: Настроит LAM
    lineinfile:
      path: /var/lib/ldap-account-manager/config/lam.conf
      create: yes
      regexp: '^#*{{ item.key }}'
      line: '{{ item.key }} {{ item.value }}'
    with_items:
      - key: "Admins:"
        value: 'cn=admin,{{ dn }}'
      - key: "treesuffix:"
        value: '{{ dn }}'
      - key: "types: suffix_user:"
        value: 'ou=People,{{ dn }}'
      - key: "types: suffix_group:"
        value: 'ou=group,{{ dn }}'
      - key: "loginSearchSuffix:"
        value: '{{ dn }}'
      - key: "loginSearchFilter:"
        value: 'cn=%USER%'
      - key: "loginMethod:"
        value: 'search'
    notify:
      - "restart php7.0-fpm"



  # - name: Добавить конфиг для nginx-proxy_pass
  #   template:
  #     src: ldap.j2
  #     dest: /etc/nginx/sites-available/ldap
  #   notify:
  #     - restart nginx-proxy
  #   delegate_to: "{{ item }}"
  #   with_items: "{{ groups['nginx-proxy'] }}"
  #   tags:
  #     - delegate
  #
  # - name: Линк для nginx-proxy_pass
  #   file:
  #     src: /etc/nginx/sites-available/ldap
  #     path: /etc/nginx/sites-enabled/ldap
  #     state: link
  #   notify:
  #     - restart nginx-proxy
  #   delegate_to: "{{ item }}"
  #   with_items: "{{ groups['nginx-proxy'] }}"
  #   tags:
  #     - delegate
