  - name: Установить роль nginx
    include_role:
      name: nginx

  - name: Установить роль postgres
    include_role:
      name: postgres

  - name: Установить роль constructive
    include_role:
      name: constructive

  - name: Установить пакеты
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      allow_unauthenticated: yes
    with_items: "{{ packages }}"
    tags:
      - install

  - name: Файл кофигурации PVVO-inner-frontend
    template:
      src: pvvo-inner.conf.j2
      dest: "/etc/nginx/conf.d/pvvo-inner.conf"
      mode: u=rwx,g=rx,o=rx
      follow: yes
    notify:
      - Перезапуск Nginx
