---

- hosts: all
  gather_facts: False
  roles:
    - known_hosts

- hosts: dyn-dns-dhcp
  roles:
    - dyn-dns-dhcp
  tags:
    - dyn-dns-dhcp

- hosts: common
  roles:
    - common
  tags:
    - common

- hosts: server-tools
  roles:
    - server-tools
  tags:
    - server-tools
