---
  - name: Установить пакеты
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      allow_unauthenticated: yes
    with_items: "{{ packages }}"
    tags:
      - install

  - name: Удалить site default
    file:
      state: absent
      path: "/etc/nginx/sites-enabled/default"

  - name: Перезапуск Nginx
    service:
      name: nginx
      state: restarted
      enabled: true
