---
  - name: Установить пакеты для Subversion
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"

  - name: Включить модули apache2
    apache2_module:
      name: "{{ item }}"
    with_items:
      - authnz_ldap
      - dav
      - dav_fs
      - dav_svn
    notify:
      - restart apache2
    tags:
      - apache_mod

  - name: Создать каталог для svn
    file:
      path: /var/lib/svn
      state: directory
      owner: www-data
      group: www-data

  - name: Распаковка svnadmin
    unarchive:
      src: https://github.com/mfreiholz/iF.SVNAdmin/archive/stable-1.6.2.tar.gz
      dest: "{{ svnadmin_path }}"
      remote_src: yes
      extra_opts:
        - --transform
        - s/iF.SVNAdmin-stable-1.6.2/svnadmin/

  - name: Распаковка WebSVN
    unarchive:
      src: http://websvn.tigris.org/files/documents/1380/49056/websvn-2.3.3.tar.gz
      dest: "/var/www"
      remote_src: yes
    tags:
      - websvn

  - name: Фиксим проверку версии
    replace:
      path: "{{ svnadmin_path }}/svnadmin/include/config.inc.php"
      regexp: 'if.*checkPHPVersion.*5.3.*'
      replace: "if (version_compare(PHP_VERSION, '5.3.0', '<')) {"

  - name: Права на папку data
    file:
      path: "{{ svnadmin_path }}/svnadmin/data"
      mode: 0777
      recurse: yes

  - name: Создать authz
    file:
      path: "{{ svnadmin_path }}/svnadmin/data/authz"
      owner: www-data
      state: touch

  - name: Настроить Apache
    template:
      src: 'apache-svn.conf.j2'
      dest: '/etc/apache2/sites-available/001-apache-svn.conf'
    notify:
      - restart apache2

  - name: Линка на конфиг apache
    file:
      src: /etc/apache2/sites-available/001-apache-svn.conf
      path: /etc/apache2/sites-enabled/001-apache-svn.conf
      state: link
    notify:
      - restart apache2

  - name: Удалить конфиг по умолчанию apache
    file:
      path: /etc/apache2/sites-enabled/000-default.conf
      state: absent
    notify:
      - restart apache2

  - name: Настройка SVNAdmin
    template:
      src: svnadmin-config.ini.j2
      dest: "{{ svnadmin_path }}/svnadmin/data/config.ini"
      owner: www-data
      group: www-data

  - name: Настройка ACL SVNAdmin
    template:
      src: svnadmin-userroleassignments.ini.j2
      dest: "{{ svnadmin_path }}/svnadmin/data/userroleassignments.ini"
      owner: www-data
      group: www-data

  - name: Скопировать config.php для websvn
    copy:
      src: /var/www/websvn-2.3.3/include/distconfig.php
      dest: /var/www/websvn-2.3.3/include/config.php
      remote_src: yes
    tags:
      - websvn

  - name: Настроить путь к svn для websvn
    lineinfile:
      path: /var/www/websvn-2.3.3/include/config.php
      regexp: '^.*\$config-\>parentPath'
      line: "$config->parentPath('/var/lib/svn');"
    tags:
      - websvn

  - name: Настроить путь к authz для websvn
    lineinfile:
      path: /var/www/websvn-2.3.3/include/config.php
      regexp: '^.*\$config-\>useAuthenticationFile'
      line: "$config->useAuthenticationFile('/var/www/svnadmin/data/authz');"
    tags:
      - websvn

  - name: Добавить About для  websvn
    replace:
      path: "/var/www/websvn-2.3.3/templates/{{ item }}"
      regexp: 'You can customize this short message in the index.tmpl of this template in order to tell your visitors what they find in your repositories.'
      replace: "Прямая сылка к репозиториям http://{{ inventory_hostname }}/repos"
    with_items:
      - calm/index.tmpl
      - Elegant/index.tmpl
      - BlueGrey/index.tmpl
    tags:
      - websvn


#
# ./templates/calm/index.tmpl
# ./templates/Elegant/index.tmpl
# ./templates/BlueGrey/index.tmpl
