  - name: Установить пакеты
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"

  - name: Файл кофигурации Bind9
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - src: 10.0.10.in-addr.arpa.zone.j2
        dest: /etc/bind/10.0.10.in-addr.arpa.zone
      - src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
      - src: named.conf.options.j2
        dest: /etc/bind/named.conf.options
    notify:
      - Перезапуск Bind9

  - name: Файл кофигурации Bind9
    template:
      src: db.domain.j2
      dest: "/etc/bind/db.{{ item.domain }}"
    with_items: "{{ object_list.groups.values() }}"
    notify:
      - Перезапуск Bind9

  - name: Перезапуск Bind9
    service:
      name: bind9
      state: restarted
